// flow-typed signature: 6031fef7b67924a670789aa39132224f
// flow-typed version: <<STUB>>/ast-pretty-print_v2.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ast-pretty-print'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ast-pretty-print' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'ast-pretty-print/index' {
  declare module.exports: $Exports<'ast-pretty-print'>;
}
declare module 'ast-pretty-print/index.js' {
  declare module.exports: $Exports<'ast-pretty-print'>;
}
