// flow-typed signature: 4ccea7c42764c6db64bf2cc39e480269
// flow-typed version: <<STUB>>/babel-plugin-tester_v5.5.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-tester'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-tester' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-tester/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-tester/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-tester/dist/index'>;
}
