// flow-typed signature: b99c5f1def43d14be105d21e9de24a35
// flow-typed version: <<STUB>>/babel-literal-to-ast_v2.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-literal-to-ast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-literal-to-ast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-literal-to-ast/dist/index' {
  declare module.exports: any;
}

declare module 'babel-literal-to-ast/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-literal-to-ast/dist/index.js' {
  declare module.exports: $Exports<'babel-literal-to-ast/dist/index'>;
}
declare module 'babel-literal-to-ast/index' {
  declare module.exports: $Exports<'babel-literal-to-ast'>;
}
declare module 'babel-literal-to-ast/index.js' {
  declare module.exports: $Exports<'babel-literal-to-ast'>;
}
declare module 'babel-literal-to-ast/src/index.js' {
  declare module.exports: $Exports<'babel-literal-to-ast/src/index'>;
}
