// flow-typed signature: 0a770de47b524c68e7ed40ad36cb2e68
// flow-typed version: <<STUB>>/babel-plugin-macros_v^2.4.5/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-macros'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-macros' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-macros/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-macros/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/index'>;
}
