// flow-typed signature: a6ad3567f1fa7fff3d72ad97f0e46189
// flow-typed version: <<STUB>>/babel-plugin-macros_v^2.5.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-macros'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-macros' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-macros/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-macros/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-macros/dist/index'>;
}
